In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Standardize

In [2]:
def standardize(x: np.array):
    return (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [3]:
x = np.random.randint(5, size=[4,4])

In [4]:
x

array([[4, 2, 4, 2],
       [0, 1, 1, 3],
       [4, 1, 0, 3],
       [3, 0, 3, 2]])

In [5]:
standardize(x)

array([[ 0.76249285,  1.41421356,  1.26491106, -1.        ],
       [-1.67748427,  0.        , -0.63245553,  1.        ],
       [ 0.76249285,  0.        , -1.26491106,  1.        ],
       [ 0.15249857, -1.41421356,  0.63245553, -1.        ]])

## Pairwise distance

In [6]:
def pairwise_dist(p, q):
    
    if p.shape[0] > q.shape[0]:
        p_flat = p[:q.shape[0], :].flatten()
        q_flat = q.flatten()
        shape = q.shape[0]
        
    elif p.shape[0] < q.shape[0]:
        q_flat = q[:p.shape[0], :].flatten()
        p_flat = p.flatten()
        shape = p.shape[0]
    
    d =  (q_flat - p_flat)**2
    d = d.reshape(shape,2)
    d = np.sqrt(np.sum(d, axis=1))
    return d


In [7]:
p = np.random.randint(10, size=[10,2])

In [8]:
q = np.random.randint(10, size=[9,2])

In [9]:
p

array([[4, 1],
       [5, 0],
       [1, 3],
       [8, 9],
       [7, 1],
       [2, 3],
       [6, 8],
       [9, 4],
       [7, 1],
       [0, 5]])

In [10]:
q

array([[7, 3],
       [9, 3],
       [6, 1],
       [0, 5],
       [1, 8],
       [5, 7],
       [8, 7],
       [5, 6],
       [5, 0]])

In [11]:
pairwise_dist(p,q)

array([3.60555128, 5.        , 5.38516481, 8.94427191, 9.21954446,
       5.        , 2.23606798, 4.47213595, 2.23606798])