In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Standardize

In [2]:
def standardize(x: np.array):
    return (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [3]:
x = np.random.randint(5, size=[4,4])

In [4]:
x

array([[2, 0, 4, 0],
       [2, 1, 3, 0],
       [0, 2, 3, 4],
       [2, 2, 0, 3]])

In [5]:
standardize(x)

array([[ 0.57735027, -1.50755672,  1.        , -0.98019606],
       [ 0.57735027, -0.30151134,  0.33333333, -0.98019606],
       [-1.73205081,  0.90453403,  0.33333333,  1.26025208],
       [ 0.57735027,  0.90453403, -1.66666667,  0.70014004]])

## Pairwise distance

In [6]:
def pairwise_dist(p, q):
    
    if p.shape[0] > q.shape[0]:
        p_flat = p[:q.shape[0], :].flatten()
        q_flat = q.flatten()
        shape = q.shape[0]
        
    elif p.shape[0] < q.shape[0]:
        q_flat = q[:p.shape[0], :].flatten()
        p_flat = p.flatten()
        shape = p.shape[0]
    
    d =  (q_flat - p_flat)**2
    d = d.reshape(shape,2)
    d = np.sqrt(np.sum(d, axis=1))
    return d


In [7]:
p = np.random.randint(10, size=[10,2])

In [8]:
q = np.random.randint(10, size=[9,2])

In [9]:
p

array([[9, 5],
       [9, 4],
       [1, 1],
       [8, 4],
       [9, 3],
       [3, 0],
       [7, 7],
       [4, 9],
       [4, 4],
       [3, 3]])

In [10]:
q

array([[8, 7],
       [5, 2],
       [9, 9],
       [6, 8],
       [7, 3],
       [3, 1],
       [6, 9],
       [5, 0],
       [1, 2]])

In [11]:
pairwise_dist(p,q)

array([ 2.23606798,  4.47213595, 11.3137085 ,  4.47213595,  2.        ,
        1.        ,  2.23606798,  9.05538514,  3.60555128])

## Max likelihood

In [16]:
class distribution:
    def __init__(self, x, mu, sigma):
        
       

In [17]:
x = np.random.randint(1, size = [4,4])

p1 = distribution(x,x,x)

C:\Users\Cyril\AppData\Local\Temp\ipykernel_13980\1745621673.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  constant = 1 / ((np.pi)**(x.shape[0]) * np.linalg.det(sigma)**0.5 )


LinAlgError: Singular matrix

In [ ]:
def max_lh(x, theta1, theta2):
    
    p1 = distribution(x, theta1[0], theta1[1]).p
    p2 = distribution(x, theta2[0], theta1[1]).p
    
    a_n = np.argmax([p1, p2])
    if a_n != 1 or a_n != 2:
        raise RuntimeError("No best likelihood was found")
    return a_n