In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [42]:
num_samples, num_features = 10, 5

In [43]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [ ]:
print(data)

In [80]:
def standardize(x):
    return np.subtract(x,np.mean(x, axis=0))/np.std(x, axis=0)
std_data = standardize(data)

In [81]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.69575894 -2.04179614  0.06865556  0.35110944 -1.491141  ]
 [-0.21687544  0.12373204  0.85470349 -1.15442202 -0.77076134]
 [ 0.44278768  0.91421462 -0.63253139 -0.30888103  1.6030958 ]
 [ 0.33846814  0.67179646 -0.06654381  0.69069535  1.28174925]
 [ 0.32828663 -1.80446066 -1.31921427  1.7432449  -0.93084717]
 [-2.88221772  0.63834344 -1.88767166  1.146729    0.50653581]
 [ 0.6144676   0.46237552  1.14586344 -0.78443098 -0.76381449]
 [-0.10815923  0.03574063  0.98866902 -1.45562569  0.99238012]
 [ 0.24545492  0.77386714 -0.24921597  0.54054561  0.09225578]
 [ 0.54202847  0.22618697  1.09728559 -0.76896458 -0.51945276]] 

 [-2.22044605e-17 -2.49800181e-17  4.44089210e-17 -8.88178420e-17
 -2.22044605e-17] 

 [1. 1. 1. 1. 1.]
