In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [14]:
print(data)

[[ 0.77339129 -3.77759408 -0.06136924  0.63686354 -0.88078221]
 [-0.28758717 -0.33210183  0.60446858 -0.38031012 -0.5148027 ]
 [ 0.42412022  0.75501775 -0.41710811  0.21033833  0.58122892]
 [ 0.49050575  0.60967277  0.14068274  0.82352553  0.60184004]
 [ 0.54254437  0.14217005  0.37334076  0.67413362  0.44183317]
 [ 0.43401399  0.61776698  0.51313824  0.65039718  0.60103895]
 [ 0.8052232   0.52164715  0.90864888  0.31923609  0.09045935]
 [ 0.30070006  0.11398436  0.82868133  0.04689632  0.62628715]
 [ 0.54758616  0.819287    0.19894754  0.8568503   0.35165264]
 [ 0.75464769  0.29596171  0.88393648  0.32551164  0.1650159 ]]


In [18]:
data[:,0]

array([ 0.77339129, -0.28758717,  0.42412022,  0.49050575,  0.54254437,
        0.43401399,  0.8052232 ,  0.30070006,  0.54758616,  0.75464769])

In [19]:
def standardize(x):
    ''' fill your code in here...
    '''
    for i in range(0, num_features):
        means = np.mean(data[:,i])
        standard_derivate = np.std(data[:,i])
        x[:,i] = (x[:,i]-means)/standard_derivate
    return x

std_data = standardize(data)

In [20]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.98160159 -2.8996421  -1.1059971   0.59775246 -2.20873602]
 [-2.5502408  -0.23841995  0.49942067 -2.1594577  -1.46519079]
 [-0.1810708   0.60124722 -1.96372775 -0.55841163  0.76157067]
 [ 0.03991694  0.48898597 -0.61882465  1.10372931  0.80344542]
 [ 0.2131459   0.12789718 -0.05785724  0.69877888  0.47836619]
 [-0.14813587  0.49523775  0.27921187  0.63443752  0.8018179 ]
 [ 1.08756538  0.42099692  1.23283719 -0.26322701 -0.23550527]
 [-0.59191851  0.10612718  1.04002547 -1.00144705  0.85311359]
 [ 0.22992928  0.65088737 -0.47834098  1.19406137  0.29515018]
 [ 0.9192069   0.24668246  1.17325252 -0.24621615 -0.08403186]] 

 [  2.77555756e-16  -5.82867088e-17   0.00000000e+00   6.66133815e-17
  -9.85322934e-17] 

 [ 1.  1.  1.  1.  1.]
