In [27]:
import numpy as np

X0 = np.array([[400, -201],
            [-800, 401]])
Y = np.array([200,-200])

In [28]:
X0

array([[ 400, -201],
       [-800,  401]])

In [29]:
Y.reshape(-1,1)

array([[ 200],
       [-200]])

In [31]:
u, s, vh = np.linalg.svd(X0)
s

array([1.00060074e+03, 3.99759848e-01])

In [32]:
np.linalg.cond(X0)

2503.0046004808573

In [30]:
np.linalg.solve(X0,Y)

array([-100., -200.])

In [34]:
X1 = np.array([[401, -201],
              [-800, 401]])

In [35]:
u, s, vh = np.linalg.svd(X1)
s

array([1.00100100e+03, 9.99000002e-04])

In [37]:
np.linalg.cond(X1)

1002003.0000501256

In [36]:
np.linalg.solve(X1,Y)

array([40000.00000034, 79800.00000068])