In [3]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [6]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
y.shape, tX.shape, ids.shape
print(y[0:3])
print(tX[0:3])
print(ids[0:3])

[ 1. -1. -1.]
[[ 1.38470e+02  5.16550e+01  9.78270e+01  2.79800e+01  9.10000e-01
   1.24711e+02  2.66600e+00  3.06400e+00  4.19280e+01  1.97760e+02
   1.58200e+00  1.39600e+00  2.00000e-01  3.26380e+01  1.01700e+00
   3.81000e-01  5.16260e+01  2.27300e+00 -2.41400e+00  1.68240e+01
  -2.77000e-01  2.58733e+02  2.00000e+00  6.74350e+01  2.15000e+00
   4.44000e-01  4.60620e+01  1.24000e+00 -2.47500e+00  1.13497e+02]
 [ 1.60937e+02  6.87680e+01  1.03235e+02  4.81460e+01 -9.99000e+02
  -9.99000e+02 -9.99000e+02  3.47300e+00  2.07800e+00  1.25157e+02
   8.79000e-01  1.41400e+00 -9.99000e+02  4.20140e+01  2.03900e+00
  -3.01100e+00  3.69180e+01  5.01000e-01  1.03000e-01  4.47040e+01
  -1.91600e+00  1.64546e+02  1.00000e+00  4.62260e+01  7.25000e-01
   1.15800e+00 -9.99000e+02 -9.99000e+02 -9.99000e+02  4.62260e+01]
 [-9.99000e+02  1.62172e+02  1.25953e+02  3.56350e+01 -9.99000e+02
  -9.99000e+02 -9.99000e+02  3.14800e+00  9.33600e+00  1.97814e+02
   3.77600e+00  1.41400e+00 -9.99000e+02  3.21

In [5]:
tX_no_outliers = tX.copy()
tX_no_outliers[tX_no_outliers == -999] = 0
print(tX_no_outliers)


tX_standardized, tX_mean, tX_std= standardize(tX_standardized)
print(tX_standardized)

[[138.47   51.655  97.827 ...   1.24   -2.475 113.497]
 [160.937  68.768 103.235 ...   0.      0.     46.226]
 [  0.    162.172 125.953 ...   0.      0.     44.251]
 ...
 [105.457  60.526  75.839 ...   0.      0.     41.992]
 [ 94.951  19.362  68.812 ...   0.      0.      0.   ]
 [  0.     72.756  70.831 ...   0.      0.      0.   ]]


NameError: name 'tX_standardized' is not defined

## Do your thing crazy machine learning thing here :) ...

In [46]:
w_initial = np.zeros(tX_standardized.shape[1])
#[weights, loss]=least_squares_GD(y, tX, w_initial, 10, 0.000001)
[weights, loss]= least_squares(y, tX_standardized)
#[weights, loss] = least_squares_SGD(y, tX, w_initial, 1000, 0.00000001)
weights, loss

(array([ 3.88857241e-02, -5.91053272e-01, -5.46678636e-01, -3.48875183e-02,
        -8.28596722e-01,  3.57637058e-02, -7.11591047e-01,  2.88153592e+01,
        -6.61943439e-03,  2.29096097e+01, -1.83948731e+01,  8.50945445e+00,
         2.84940447e+01, -2.22203109e+01, -7.41586750e-02, -4.44509261e-02,
        -2.18359691e+01, -1.83714253e-02,  1.13074425e-01,  2.57779664e-01,
         4.01629576e-02, -3.92161700e-02,  1.22475267e+00,  2.14143727e-01,
         2.99820109e-02,  9.53216282e-04,  9.66557697e-02,  9.95320306e-02,
        -1.63590161e-01, -2.31510175e+01]), 0.3390172811873623)

### Generate predictions and save ouput in csv format for submission:

In [53]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download test data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [56]:
OUTPUT_PATH = '../data/pred.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)