In [22]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [37]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
y.shape, tX.shape

((250000,), (250000, 30))

In [47]:
tX_no_outliers = tX.copy()
tX_no_outliers[tX_no_outliers == -999] = 0
print(tX_no_outliers)


tX_standardized, tX_mean, tX_std= standardize(tX_standardized)
print(tX_standardized)

[[138.47   51.655  97.827 ...   1.24   -2.475 113.497]
 [160.937  68.768 103.235 ...   0.      0.     46.226]
 [  0.    162.172 125.953 ...   0.      0.     44.251]
 ...
 [105.457  60.526  75.839 ...   0.      0.     41.992]
 [ 94.951  19.362  68.812 ...   0.      0.      0.   ]
 [  0.     72.756  70.831 ...   0.      0.      0.   ]]
[[ 1.22443381  0.19387987  0.74197336 ... -0.40458096 -0.44868057
   0.92798707]
 [ 1.4911326   0.39702299  0.80617005 ... -0.41930061 -0.41930061
   0.1294339 ]
 [-0.41930061  1.5057929   1.07584839 ... -0.41930061 -0.41930061
   0.10598928]
 ...
 [ 0.83254673  0.29918476  0.48096063 ... -0.41930061 -0.41930061
   0.0791734 ]
 [ 0.70783326 -0.18946032  0.3975453  ... -0.41930061 -0.41930061
  -0.41930061]
 [-0.41930061  0.4443633   0.42151222 ... -0.41930061 -0.41930061
  -0.41930061]]


## Do your thing crazy machine learning thing here :) ...

In [46]:
w_initial = np.zeros(tX_standardized.shape[1])
#[weights, loss]=least_squares_GD(y, tX, w_initial, 10, 0.000001)
[weights, loss]= least_squares(y, tX_standardized)
#[weights, loss] = least_squares_SGD(y, tX, w_initial, 1000, 0.00000001)
weights, loss

(array([ 3.88857241e-02, -5.91053272e-01, -5.46678636e-01, -3.48875183e-02,
        -8.28596722e-01,  3.57637058e-02, -7.11591047e-01,  2.88153592e+01,
        -6.61943439e-03,  2.29096097e+01, -1.83948731e+01,  8.50945445e+00,
         2.84940447e+01, -2.22203109e+01, -7.41586750e-02, -4.44509261e-02,
        -2.18359691e+01, -1.83714253e-02,  1.13074425e-01,  2.57779664e-01,
         4.01629576e-02, -3.92161700e-02,  1.22475267e+00,  2.14143727e-01,
         2.99820109e-02,  9.53216282e-04,  9.66557697e-02,  9.95320306e-02,
        -1.63590161e-01, -2.31510175e+01]), 0.3390172811873623)

### Generate predictions and save ouput in csv format for submission:

In [53]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download test data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [56]:
OUTPUT_PATH = '../data/pred.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)